# prettier-ignore
specVersion: 0.0.4
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: FairLaunch
    network: {{ network }}
    source:
      address: "{{ FairLaunch.address }}"
      abi: FairLaunch
      startBlock: {{ FairLaunch.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: FairLaunch
          file: ./abis/FairLaunch.json
        - name: Vault
          file: ./abis/Vault.json
        - name: IERC20Detailed
          file: ./abis/IERC20Detailed.json
        - name: IERC20DetailedBytes
          file: ./abis/IERC20DetailedBytes.json
      eventHandlers:
        - event: Deposit(indexed address,indexed uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed uint256,uint256)
          handler: handleWithdraw
        - event: OwnershipTransferred(indexed address,indexed address)
          handler: ownership
      file: ./protocols/alpaca-finance-lending/src/mappings/FairLaunch.ts
templates:
  - kind: ethereum
    name: Shield
    network: {{ network }}
    source:
      abi: Shield
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: Shield
          file: ./abis/Shield.json
      eventHandlers:
        - event: AddPool(indexed uint256,uint256,indexed address)
          handler: handleAddPool
      file: ./protocols/alpaca-finance-lending/src/mappings/FairLaunch.ts
  - kind: ethereum
    name: Vault
    network: {{ network }}
    source:
      abi: Vault
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: Vault
          file: ./abis/Vault.json
        - name: IERC20Detailed
          file: ./abis/IERC20Detailed.json
        - name: IERC20DetailedBytes
          file: ./abis/IERC20DetailedBytes.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleOutputTokenTransfer
      file: ./protocols/alpaca-finance-lending/src/mappings/FairLaunch.ts
