# prettier-ignore
specVersion: 0.0.4
repository: https://github.com/messari/subgraphs
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: FairLaunch
    network: {{ network }}
    source:
      address: "{{ FairLaunch.address }}"
      abi: FairLaunch
      startBlock: {{ FairLaunch.startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities: []
      abis:
        - name: FairLaunch
          file: ./abis/FairLaunch.json
      callHandlers:
        - function: addPool(uint256,address,bool)
          handler: addPool
      file: ./protocols/alpaca-finance-lending/src/mappings/FairLaunch.ts


